## Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
arr_two = np.array(my_mat)

In [6]:
print arr_two

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [12]:
np.zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [13]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [14]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

Linspace dipakai untuk generate matrix dari "start" ke "end" sejumlah "N". Sebagai contoh, jika kita ingin generate N=10 angka dari 0-5 maka

In [17]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

Matrix identitas dapat dibuat dengan fungsi "eye"

In [18]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

Matrix random dsitribusi uniform dari 0 sampai 1

In [22]:
np.random.rand(5)

array([ 0.05018544,  0.58963612,  0.55995322,  0.6818129 ,  0.10478103])

In [23]:
np.random.rand(3,5)

array([[ 0.59488169,  0.79344658,  0.89004728,  0.0849715 ,  0.09644912],
       [ 0.81978476,  0.59580258,  0.14088802,  0.06717987,  0.33353135],
       [ 0.59257525,  0.43872137,  0.9002342 ,  0.28898322,  0.42820524]])

Matrix random dengan distribusi normal

In [26]:
np.random.randn(2)

array([ 0.52510392,  1.03859851])

In [27]:
np.random.randn(4,4)

array([[-0.79784702,  1.69664506,  0.45339802,  0.06023519],
       [-0.74177102, -0.85324293,  1.22933357,  0.92380701],
       [ 0.45728812,  1.25740887, -1.07924572,  0.22979522],
       [-0.92547685, -0.20308345,  1.13198277,  0.52019446]])

Matrix random integer

Random vector 1x10 antara 1 sampai 100

In [32]:
 np.random.randint(1,100,10)

array([98, 50, 74, 96, 66, 18, 71, 54, 27,  1])

Random matrix 4x4 dari 1 sampai 100

In [36]:
 np.random.randint(1,100,(4,4))

array([[28, 72, 16, 19],
       [ 6,  3, 47, 58],
       [88, 12, 67, 19],
       [ 1, 26, 57, 20]])

Reshape dimensi matrix

In [37]:
arr = np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Cari max dan min

In [42]:
ran_arr = np.random.randint(0,100,10)

In [43]:
ran_arr

array([91, 36, 29, 20, 96, 32, 63, 87, 11, 18])

In [44]:
ran_arr.max()

96

In [45]:
ran_arr.min()

11

In [46]:
ran_arr.shape

(10,)

Cari index dari bilangan terbesar dan terkecil

In [47]:
ran_arr.argmax()

4

In [48]:
ran_arr.argmin()

8

Lihat ukuran matrix dan reshape

In [49]:
ran_arr.shape

(10,)

In [51]:
ran_arr.reshape(2,5)

array([[91, 36, 29, 20, 96],
       [32, 63, 87, 11, 18]])

In [52]:
ran_arr.reshape(5,2)


array([[91, 36],
       [29, 20],
       [96, 32],
       [63, 87],
       [11, 18]])

In [53]:
ran_arr.reshape(10,1)

array([[91],
       [36],
       [29],
       [20],
       [96],
       [32],
       [63],
       [87],
       [11],
       [18]])

In [54]:
arr.dtype

dtype('int64')